### ISSUE TITLE
OCS2_legged_robot test launch bug.

### ISSUE THREAD

**Issue by Zcyyy** [leggedrobotics/ocs2#29]
**Describe the bug**
An error was reported while running `roslaunch ocs2_legged_robot legged_robot.launch`

**Expected behavior**

**Screenshots**
![2021-12-30_11-17](https://user-images.githubusercontent.com/27263450/147718949-3cf66b2a-ae83-4876-aa0e-1264f6083379.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version: 20.04

**Comment by rubengrandia** [comment]
Thanks for reporting. This error is due to an assert that should not have been there anymore. This will be fixed in the next release. For now you can build in release mode or remove the failing asserts here:
https://github.com/leggedrobotics/ocs2/blob/b037d819c9a02a674de9badb628b32646ce11d6a/ocs2_robotic_examples/ocs2_legged_robot/src/foot_planner/CubicSpline.cpp#L106
https://github.com/leggedrobotics/ocs2/blob/b037d819c9a02a674de9badb628b32646ce11d6a/ocs2_robotic_examples/ocs2_legged_robot/src/foot_planner/CubicSpline.cpp#L107

**Comment by Zcyyy** [comment]
Thank you very much!
> 
> 
> https://github.com/leggedrobotics/ocs2/blob/b037d819c9a02a674de9badb628b32646ce11d6a/ocs2_robotic_examples/ocs2_legged_robot/src/constraint/EndEffectorLinearConstraint.cpp#L62-L67
also need to remove.After remove these bugs,the code works perfectly.
