### ISSUE TITLE
Hard inequality constraints for a simple MPC

### ISSUE THREAD

**Issue by TarekEl-Agroudi** [leggedrobotics/ocs2#40]
Dear ocs2 developers,

I am looking into using ocs2 for implementing an MPC controller for a ship. Impressive library! I have got the library running and was wondering if you could help me with a small query:

In the library documentation, the optimal control problem is given with an inequality constraint h(x,u,t) >= 0. However, I can only see a way to set an inequality Lagrangian (see the attached screenshot). For our application, we would need hard inequality constraints on the state and input, and I was wondering if there is a way to set this h(x,u,t) function instead of using the inequality lagrangian?

Our model is as of now a simple forced harmonic oscillator, and the application is very similar to the double integrator example. Furthermore, due to hardware reasons, I cannot use ROS and am calling the optimization algorithms directly through the advanceMpc method. 

![image](https://user-images.githubusercontent.com/76074091/177788587-d079ab71-35ca-45b7-b3b2-9cece789b2b5.png)

**Comment by farbod-farshidian** [comment]
None of the current solvers handles inequality constraints directly. The main reason is computational overhead. However, since the realse 11.0, the DDP-based solvers handle the inequality constraints through an Augmented Lagrangian (AL) approach, which works considerably better than our previous penalty-based method. The technical detail of this AL approach can be found in this [paper](https://arxiv.org/pdf/2101.06067.pdf).

For an example, refer to _ocs2_cartpole/src/CartPoleInterface.cpp_ and _ocs2_cartpole/test/testCartpole.cpp_.
