### ISSUE TITLE
Legged robot raisim example is unstable

### ISSUE THREAD

**Issue by Kate88L** [leggedrobotics/ocs2#56]
Hello,

when running the legged_robot_raisim example the pose of the robot immediately changes, the center of mass moves slightly in the x direction and contact forces of the front legs change the orientation. The robot is in some kind of an unstable state and the optimal forces oscillate slightly. After a while, even without any gait command, the right hind leg starts to float in the air and the computation crushes. 

Is this a bug or is it due to the use of raisim simulator on a simplified model?

This is the pose of the robot after 2 seconds of the simulation. No gait commanded, no trajectory commanded.

![image](https://user-images.githubusercontent.com/115641647/199671235-9f2febac-c09e-4ea4-ace0-7605e9b40b3e.png)

**Comment by matheecs** [comment]
I had the same problem. Do I need to tune the joint Kp and Kd gain, or change the parameters of RaiSim?

![ocs2_raisim_demo](https://user-images.githubusercontent.com/16047052/199719324-b11293fc-19d6-43f4-bf17-34d73075baf7.gif)

**Comment by matheecs** [comment]
Do we have to implement a WBC controller for simulation?

**Comment by areske** [comment]
Hi @Kate88L and @matheecs,

This is not due to the use of a simplified robot model and no need to tune gains or implement WBC. The main issue here is that for the positionErrorGain in the ZeroVelocityConstraint for the EE it is currently assumed that the terrain is flat. You have two options:

1. Set the generateTerrain flag to false (recommended if flat terrain works for you): https://github.com/leggedrobotics/ocs2/blob/main/ocs2_raisim/ocs2_legged_robot_raisim/config/raisim.info#L11
2. Set the positionErrorGain to 0.0 (recommended if you need rough terrain): https://github.com/leggedrobotics/ocs2/blob/main/ocs2_robotic_examples/ocs2_legged_robot/config/mpc/task.info#L12

@farbod-farshidian FYI

**Comment by Kate88L** [comment]
Works like a charm. Thanks for the quick reply  :)
